name: Multi-platform AmneziaWG Docker build

on:
  push:

env: 
  DOCKER_CONTAINER_REGISTRY: ghcr.io


jobs:
  build:
    name: Build AmneziaWG ${{ matrix.IMAGE_POSTFIX }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - TARGETPLATFORM: linux/arm/v7
            TARGETARCH: arm
            TARGETVARIANT: 7
            IMAGE_POSTFIX: armv7
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        env: 
          DOCKER_BUILD_SUMMARY: false
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          platforms: ${{ matrix.TARGETPLATFORM }}
          build-args: |
            TARGETOS=linux
            TARGETARCH=${{ matrix.TARGETARCH }}
            TARGETVARIANT=${{ matrix.TARGETVARIANT }}
          tags: |
            ${{ env.DOCKER_CONTAINER_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}-${{ matrix.IMAGE_POSTFIX}}:latest
            ${{ env.DOCKER_CONTAINER_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}-${{ matrix.IMAGE_POSTFIX}}:${{ github.run_number }}